
spring:
  application:
    name: CoCe-ConfigurationService
    frontend-url: ${FRONTEND_URL:http://localhost:5173/}
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/coce_configurations}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${CONFIGURATION_SERVICE_PORT:8080}
